In [1]:
import numpy as np
import pandas as pd

In [14]:
data = pd.read_csv("IRIS.csv")

In [15]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [16]:
X = data.drop(['species'],axis=1)
y = data['species'].map({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2})

In [17]:
N = y.value_counts()

In [18]:
indices = []
for i in range(3):
    indices.append(y[y==i].index)

In [19]:
means=[]
for i in range(3):
    means.append(np.mean(X.loc[indices[i]],axis=0))

 

In [20]:
m = np.mean(X,axis=0)

In [21]:
cov = np.dot(((X)-m).T,(X)-m)

In [22]:
cov

array([[102.16833333,  -5.851     , 189.77866667,  77.01866667],
       [ -5.851     ,  28.0126    , -47.9352    , -17.5792    ],
       [189.77866667, -47.9352    , 463.86373333, 193.16173333],
       [ 77.01866667, -17.5792    , 193.16173333,  86.77973333]])

In [23]:
def linear_model(X,mean,cov):
    covinv = np.linalg.inv(cov)
    a = np.dot(np.dot(mean.T,covinv.T),X)
    w = -0.5*np.dot(mean.T,np.dot(covinv,mean))+np.log(1/3)
    return a+w

In [24]:
posterior = []
X1 = np.array(X)
for i in range(150):
    row=[]
    s = []
    for k in range(3):
        s.append(np.exp(linear_model(X1[i],means[k],cov)))
    for j in range(3):
        norm = np.sum(s)
        row.append(s[j]/norm)
    posterior.append(row)

In [25]:
predictions = np.argmax(posterior, axis=1)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, predictions)
print(cm)
accuracy_score(y, predictions)

[[49  1  0]
 [ 0 42  8]
 [ 0 11 39]]


0.8666666666666667